{"content": {"suites": {"0": {"status": {"total_pass": 16, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 4, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_5_InputBidangGiatja", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_6_InputJenisKegiatanKerja", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_7_namaKegiatan", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_8_skalaKegiatan", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_9_tanggalAwalKegiatan", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_10_tanggalAkhirKegiatan", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_11_AreaKegiatan", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_12_lokasiKegiatan", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_13_luas", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_14_jumlahRuang", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_15_sarana", "rerun": "0"}, "15": {"status": "PASS", "message": "", "test_name": "test_16_prasarana", "rerun": "0"}, "16": {"status": "FAIL", "message": "   selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input type=\"text\" class=\"el-select__input\" autocomplete=\"off\" style=\"margin-left: 11px; flex-grow: 1; width: 0.0189934%; max-width: 1043px;\"> is not clickable at point (827, 486). Other element would receive the click: <li class=\"el-select-group__title\">...</li>\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x0000000104615ae8 chromedriver + 4958952\n   1   chromedriver                        0x000000010460d7b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001041cf1d6 chromedriver + 475606\n   3   chromedriver                        0x000000010421c321 chromedriver + 791329\n   4   chromedriver                        0x000000010421936e chromedriver + 779118\n   5   chromedriver                        0x0000000104215fd4 chromedriver + 765908\n   6   chromedriver                        0x00000001042149af chromedriver + 760239\n   7   chromedriver                        0x0000000104205283 chromedriver + 696963\n   8   chromedriver                        0x0000000104238c12 chromedriver + 908306\n   9   chromedriver                        0x00000001042048f1 chromedriver + 694513\n   10  chromedriver                        0x0000000104238dce chromedriver + 908750\n   11  chromedriver                        0x000000010425425b chromedriver + 1020507\n   12  chromedriver                        0x00000001042389e3 chromedriver + 907747\n   13  chromedriver                        0x0000000104202aef chromedriver + 686831\n   14  chromedriver                        0x000000010420400e chromedriver + 692238\n   15  chromedriver                        0x00000001045d19ad chromedriver + 4680109\n   16  chromedriver                        0x00000001045d6c12 chromedriver + 4701202\n   17  chromedriver                        0x00000001045dd79f chromedriver + 4728735\n   18  chromedriver                        0x00000001045d7b7a chromedriver + 4705146\n   19  chromedriver                        0x00000001045aa27e chromedriver + 4518526\n   20  chromedriver                        0x00000001045f7908 chromedriver + 4835592\n   21  chromedriver                        0x00000001045f7a87 chromedriver + 4835975\n   22  chromedriver                        0x000000010460700f chromedriver + 4898831\n   23  libsystem_pthread.dylib             0x00007ff8161cb1d3 _pthread_start + 125\n   24  libsystem_pthread.dylib             0x00007ff8161c6bd3 thread_start + 15\n       assert False\n", "test_name": "test_17_mitra", "rerun": "0"}, "17": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x127a5a2b0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=55212): Max retries exceeded with url: /session/c3dd9c6eeaa16349ea01ec71620984a8/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x127a5a2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_18_InputGambar", "rerun": "0"}, "18": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x127d74100>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=55212): Max retries exceeded with url: /session/c3dd9c6eeaa16349ea01ec71620984a8/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x127d74100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_19_Keterangan", "rerun": "0"}, "19": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x127cfb430>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=55212): Max retries exceeded with url: /session/c3dd9c6eeaa16349ea01ec71620984a8/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x127cfb430>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_32_exit", "rerun": "0"}}, "suite_name": "1.KegiatanKerja/Fungsional/test_GiatjaTambah.py"}}}, "date": "May 02, 2023", "start_time": 1683012376.643821, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "16", "fail": "4", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "20"}