{"content": {"suites": {"0": {"status": {"total_pass": 5, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_5_InputBidangGiatja", "rerun": "0"}, "5": {"status": "FAIL", "message": "   selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x00000001049e3ae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001049db7b3 chromedriver + 4925363\n   2   chromedriver                        0x000000010459d1d6 chromedriver + 475606\n   3   chromedriver                        0x00000001045a1274 chromedriver + 492148\n   4   chromedriver                        0x00000001045a0e56 chromedriver + 491094\n   5   chromedriver                        0x00000001045a12fc chromedriver + 492284\n   6   chromedriver                        0x00000001045ea093 chromedriver + 790675\n   7   chromedriver                        0x00000001045e7144 chromedriver + 778564\n   8   chromedriver                        0x00000001045e3fd4 chromedriver + 765908\n   9   chromedriver                        0x00000001045e29af chromedriver + 760239\n   10  chromedriver                        0x00000001045d3283 chromedriver + 696963\n   11  chromedriver                        0x0000000104606c12 chromedriver + 908306\n   12  chromedriver                        0x00000001045d28f1 chromedriver + 694513\n   13  chromedriver                        0x0000000104606dce chromedriver + 908750\n   14  chromedriver                        0x000000010462225b chromedriver + 1020507\n   15  chromedriver                        0x00000001046069e3 chromedriver + 907747\n   16  chromedriver                        0x00000001045d0aef chromedriver + 686831\n   17  chromedriver                        0x00000001045d200e chromedriver + 692238\n   18  chromedriver                        0x000000010499f9ad chromedriver + 4680109\n   19  chromedriver                        0x00000001049a4c12 chromedriver + 4701202\n   20  chromedriver                        0x00000001049ab79f chromedriver + 4728735\n   21  chromedriver                        0x00000001049a5b7a chromedriver + 4705146\n   22  chromedriver                        0x000000010497827e chromedriver + 4518526\n   23  chromedriver                        0x00000001049c5908 chromedriver + 4835592\n   24  chromedriver                        0x00000001049c5a87 chromedriver + 4835975\n   25  chromedriver                        0x00000001049d500f chromedriver + 4898831\n   26  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   27  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n       assert False\n", "test_name": "test_20_tambahPeserta", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12752adf0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=60420): Max retries exceeded with url: /session/06b9c67ff13444dc97a5dc53c037cd89/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12752adf0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_32_exit", "rerun": "0"}}, "suite_name": "1.KegiatanKerja/Fungsional/test_GiatjaTambah.py"}}}, "date": "May 03, 2023", "start_time": 1683090222.435568, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "5", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "7"}