{"content": {"suites": {"0": {"status": {"total_pass": 3, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message: \n   Stacktrace:\n   0   chromedriver                        0x00000001028e4ae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001028dc7b3 chromedriver + 4925363\n   2   chromedriver                        0x000000010249e1d6 chromedriver + 475606\n   3   chromedriver                        0x00000001024e1a20 chromedriver + 752160\n   4   chromedriver                        0x00000001024e1c81 chromedriver + 752769\n   5   chromedriver                        0x0000000102525f64 chromedriver + 1032036\n   6   chromedriver                        0x0000000102507c3d chromedriver + 908349\n   7   chromedriver                        0x000000010252325b chromedriver + 1020507\n   8   chromedriver                        0x00000001025079e3 chromedriver + 907747\n   9   chromedriver                        0x00000001024d1aef chromedriver + 686831\n   10  chromedriver                        0x00000001024d300e chromedriver + 692238\n   11  chromedriver                        0x00000001028a09ad chromedriver + 4680109\n   12  chromedriver                        0x00000001028a5c12 chromedriver + 4701202\n   13  chromedriver                        0x00000001028ac79f chromedriver + 4728735\n   14  chromedriver                        0x00000001028a6b7a chromedriver + 4705146\n   15  chromedriver                        0x000000010287927e chromedriver + 4518526\n   16  chromedriver                        0x00000001028c6908 chromedriver + 4835592\n   17  chromedriver                        0x00000001028c6a87 chromedriver + 4835975\n   18  chromedriver                        0x00000001028d600f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff8161cb1d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff8161c6bd3 thread_start + 15\n       assert False\n", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11e088370>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=57176): Max retries exceeded with url: /session/739e23b409cfe8de8bb7194adce21447/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11e088370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_32_exit", "rerun": "0"}}, "suite_name": "1.KegiatanKerja/Fungsional/test_GiatjaTambah.py"}}}, "date": "May 02, 2023", "start_time": 1682995892.0026119, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "3", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "5"}