{"content": {"suites": {"0": {"status": {"total_pass": 15, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_5_NamaInput", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_6_KronologisKejadianFkr", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_7_TanggalPemberianBantuanHukumFkr", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_8_MelanggarPeraturanPerundangundanganFkr", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_9_PemberiBantuanHukumFkr", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_10_PertimbanganHukumFkr", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_11_PutusanPengadilanFkr", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_12_KeteranganFkr", "rerun": "0"}, "12": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117c013d0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59515): Max retries exceeded with url: /session/f53e14f10486cd0d5b44ef2ba7653526/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117c013d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117c01b20>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59515): Max retries exceeded with url: /session/f53e14f10486cd0d5b44ef2ba7653526/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117c01b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_13_ClickButtonSimpan", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_10_SetupOs", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_11_LoginSPV", "rerun": "0"}, "15": {"status": "PASS", "message": "", "test_name": "test_28_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/11.Laporan8A/Fungsional/test_Laporan8A.py"}}}, "date": "April 26, 2023", "start_time": 1682482312.239093, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "15", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "16"}