{"content": {"suites": {"0": {"status": {"total_pass": 3, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_13_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_14_LoginSPV", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_15_AksesMenuSpv", "rerun": "0"}, "3": {"status": "FAIL", "message": "   selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span class=\"\">...</span> is not clickable at point (1179, 762). Other element would receive the click: <div class=\"el-loading-mask\" style=\"\">...</div>\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x00000001024faae8 chromedriver + 4958952\n   1   chromedriver                        0x00000001024f27b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001020b41d6 chromedriver + 475606\n   3   chromedriver                        0x0000000102101321 chromedriver + 791329\n   4   chromedriver                        0x00000001020fe36e chromedriver + 779118\n   5   chromedriver                        0x00000001020fafd4 chromedriver + 765908\n   6   chromedriver                        0x00000001020f99af chromedriver + 760239\n   7   chromedriver                        0x00000001020ea283 chromedriver + 696963\n   8   chromedriver                        0x000000010211dc12 chromedriver + 908306\n   9   chromedriver                        0x00000001020e98f1 chromedriver + 694513\n   10  chromedriver                        0x000000010211ddce chromedriver + 908750\n   11  chromedriver                        0x000000010213925b chromedriver + 1020507\n   12  chromedriver                        0x000000010211d9e3 chromedriver + 907747\n   13  chromedriver                        0x00000001020e7aef chromedriver + 686831\n   14  chromedriver                        0x00000001020e900e chromedriver + 692238\n   15  chromedriver                        0x00000001024b69ad chromedriver + 4680109\n   16  chromedriver                        0x00000001024bbc12 chromedriver + 4701202\n   17  chromedriver                        0x00000001024c279f chromedriver + 4728735\n   18  chromedriver                        0x00000001024bcb7a chromedriver + 4705146\n   19  chromedriver                        0x000000010248f27e chromedriver + 4518526\n   20  chromedriver                        0x00000001024dc908 chromedriver + 4835592\n   21  chromedriver                        0x00000001024dca87 chromedriver + 4835975\n   22  chromedriver                        0x00000001024ec00f chromedriver + 4898831\n   23  libsystem_pthread.dylib             0x00007ff80731f1d3 _pthread_start + 125\n   24  libsystem_pthread.dylib             0x00007ff80731abd3 thread_start + 15\n       assert False\n", "test_name": "test_16_KirimLaporanSpv", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x131f2d310>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=51141): Max retries exceeded with url: /session/461c6331c4b537f22b022a08ce201340/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x131f2d310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_31_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/12.Laporan8B/Fungsional/test_laporan8B.py"}}}, "date": "May 02, 2023", "start_time": 1682991317.709962, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "3", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "5"}